require('./is.test')
require('./map.test')
require('./omit.test')
require('./pick.test')
require('./size.test')
require('./prop.test')
require('./uniq.test')
require('./curry.test')
require('./case.test')
require('./getType.test')
require('./composeAndPipe.test')
require('./memoize.test')
require('./has.test');
require('./shim.test');
require('./isPrimitive.test');
