import tape from "tape"
import toHashCode from "../src/toHashCode"

const bagOfWords = [
  "red",
  "orange",
  "yellow",
  "green",
  "blue",
  "indigo",
  "violet",
  "black",
  "white",
  "grey",
  "one",
  "two",
  "three",
  "four",
  "five",
  "six",
  "seven",
  "eight",
  "nine",
  "ten",
  "eleven",
  "twelve",
  "thirteen",
  "fourteen",
  "fifteen",
  "sixteen",
  "seventeen",
  "eighteen",
  "nineteen",
  "twenty",
  "coffee",
  "tea",
  "juice",
  "milk",
  "water",
  "beer",
  "wine",
  "apple",
  "orange",
  "grape",
  "banana",
  "pear",
  "pineapple",
  "raspberry",
  "blueberry",
  "mango",
  "papaya",
  "plum",
  "strawberry",
  "cherry",
  "peach",
  "carrot",
  "potato",
  "tomato",
  "onion",
  "cucumber",
  "broccoli",
  "cauliflower",
  "pea",
  "eggplant",
  "squash",
  "beet",
  "radish",
  "zuccini",
  "pumpkin",
  "pinto",
  "garbanzo",
  "jalapeno",
  "serano",
  "habanero",
  "boat",
  "plane",
  "car",
  "truck",
  "motorcycle",
  "moped",
  "bicycle",
  "scooter",
  "skateboard",
  "skates",
  "house",
  "apartment",
  "trailer",
  "mansion",
  "castle",
  "dog",
  "cat",
  "mouse",
  "snake",
  "lizard",
  "monkey",
  "horse",
  "cow",
  "sheep",
  "pig",
  "goat",
  "deer",
  "chicken",
  "turkey",
  "rabbit",
  "eagle"
]

tape("\"toHashCode\" generates a numeric hash value for a given string", t => {
  t.equal(toHashCode("vanilla"), 15)
  t.equal(toHashCode("vanilla", 500), 243, "with a high limit")

  const hashes = Array(100).fill(0)
  for (let i = 0; i < 100; i++) {
    const idx = toHashCode(bagOfWords[i], 100)
    hashes[idx] = (hashes[idx] || 0) + 1
  }

  t.ok(hashes.some(val => val === 0), "some indexes weren't filled")
  t.ok(hashes.some(val => val > 1), "there were also some collisions")
  
  t.end()
})
