module.exports = {
  profiles: [
    { name: "john", age: 82, favorites: { color: "red", timeOfDay: "mornings" } },
    { name: "jim", age: 72, favorites: { color: "red", timeOfDay: "naptime" } },
    { name: "jeff", age: 62, favorites: { color: "blue", timeOfDay: "naptime" } },
    { name: "giovanni", age: 52, favorites: { color: "green", timeOfDay: "evening" } },
    { name: "giancarlo", age: 42, favorites: { color: "red", timeOfDay: "evening" } },
    { name: "josef", age: 32, favorites: { color: "red", timeOfDay: "mornings" } },
    { name: "jan", age: 32, favorites: { color: "yellow", timeOfDay: "mornings" } },
    { name: "johnson", age: 22, favorites: { color: "blue", timeOfDay: "evening" } }
  ],
  magic: {
    Malfoy: {
      "Lucius and Narcissa": {
        sons: ["Draco"]
      }
    },
    Potter: {
      "James and Lily": {
        sons: ["Harry"]
      }
    },
    Weasley: {
      "Arthur and Molly": {
        sons: ["Percy", "Charlie", "Bill", "Fred", "George", "Ronald"],
        daughters: ["Ginny"]
      }
    }
  },
  magicWithoutKids: {
    Black: {
      Regulus: {},
      Sirius: {}
    },
    Dumbledore: {
      Albus: {},
      Adriana: {},
      Aberforth: {}
    },
    Snape: {
      Severus: {}
    }
  },
  counterCultureIcons: {
    Hoffman: "albert",
    Leary: "timothy",
    Ginsberg: "allen"
  },
  composers: {
    Williams: "ralph vaughan",
    SaintSaens: "camille",
    Mahler: "gustav",
    Wagner: "richard"
  },
  hook: {
    Hoffman: "dustin",
    Williams: "robin",
    Roberts: "julia",
    Hoskins: "bob"
  },
  sphere: {
    Hoffman: "dustin",
    Jackson: "samuel",
    Stone: "sharon",
    Latifah: "queen"
  },
  jurrassicPark: {
    Neill: "sam",
    Jackson: "samuel",
    Knight: "wayne",
    Goldblum: "jeff"
  },
  solarSystem: {
    Saturn: {
      greek: "Kronos",
      moons: ["Titan", "Enceladus", "Mimas"]
    },
    Jupiter: {
      greek: "Zeuss",
      moons: ["Europa", "Ganymede", "Lo"]
    },
    Sun: "Apollo",
    Neptune: {
      greek: "Poseidon",
      moons: ["Triton"]
    },
    Venus: "Aphrodite",
    Mars: {
      greek: "Aries",
      moons: ["Phobos", "Deimos"]
    },
    Mercury: {
      greek: "Hermes"
    }
  },
  pantheon: {
    Sun: "Apollo",
    Mercury: {
      greek: "Hermes"
    },
    Venus: "Aphrodite",
    Mars: {
      greek: "Aries",
      moons: ["Phobos", "Deimos"]
    },
    Jupiter: {
      greek: "Zeuss",
      moons: ["Europa", "Ganymede", "Lo"]
    },
    Saturn: {
      greek: "Kronos",
      moons: ["Titan", "Enceladus", "Mimas"]
    },
    Neptune: {
      greek: "Poseidon",
      moons: ["Triton"]
    }
  },
  spices: {
    Brown: "Scary Spice",
    Chisholm: "Sporty Spice",
    Bunton: "Baby Spice",
    Halliwell: "Ginger Spice",
    Beckham: "Posh Spice"
  },
  companies: [
    { name: "Kreiger - Denesik", uri: "https://chadrick.net" },
    { name: "Bogisich Group", uri: "http://adriel.name" },
    { name: "Shanahan - Berge", uri: "https://lorenza.com" },
    { name: "Treutel, Buckridge and Crist", uri: "https://ignacio.biz" },
    { name: "Nitzsche - Waters", uri: "http://flossie.info" },
    { name: "Dicki Group", uri: "http://lucas.net" },
    { name: "Braun - Turcotte", uri: "http://pete.name" },
    { name: "Rolfson, Tremblay and DuBuque", uri: "https://lisandro.biz" },
    { name: "Collier, Schulist and Huel", uri: "https://liana.org" },
    { name: "Kovacek, Reynolds and Hammes", uri: "https://hank.net" },
    { name: "Harris, Sipes and Littel", uri: "https://demario.name" },
    { name: "Treutel, Kuhlman and Nienow", uri: "http://lucius.com" },
    { name: "Berge LLC", uri: "https://jason.name" },
    { name: "Lakin, Stroman and Hagenes", uri: "https://emmanuelle.info" },
    { name: "Flatley - Lakin", uri: "https://ila.name" },
    { name: "Hammes - Schamberger", uri: "http://matteo.net" },
    { name: "Johnston, O'Kon and Lubowitz", uri: "http://hope.biz" },
    { name: "Kessler - Wyman", uri: "http://courtney.com" },
    { name: "Dickinson, Orn and Gerlach", uri: "http://rosella.com" },
    { name: "Will, Senger and Parker", uri: "https://percy.name" },
    { name: "Corwin, Block and Davis", uri: "http://dedrick.com" },
    { name: "Dooley, Kerluke and Wisoky", uri: "https://orion.org" },
    { name: "Glover - Becker", uri: "https://demetris.net" },
    { name: "Bogisich Inc", uri: "http://lavern.biz" },
    { name: "Gerhold, Kilback and Koepp", uri: "https://pasquale.info" },
    { name: "Beer - Bernhard", uri: "http://julia.name" },
    { name: "Lakin, Lemke and O'Hara", uri: "http://dixie.net" },
    { name: "Gusikowski and Sons", uri: "https://dallin.org" },
    { name: "Russel, Collier and Lowe", uri: "http://claude.org" },
    { name: "Rolfson - Nolan", uri: "https://johnathon.name" },
    { name: "Lowe, Jacobson and Champlin", uri: "https://andre.net" },
    { name: "Kreiger - Schaefer", uri: "http://orrin.info" },
    { name: "Kozey, Ullrich and Kautzer", uri: "http://eldred.biz" },
    { name: "Friesen - Watsica", uri: "http://alanna.com" },
    { name: "Thompson Inc", uri: "https://derick.org" },
    { name: "Williamson - Zemlak", uri: "http://amos.com" },
    { name: "Schroeder - Fay", uri: "http://delphia.info" },
    { name: "Maggio, Konopelski and Rice", uri: "http://donnie.org" },
    { name: "Hauck - Pouros", uri: "http://reyna.net" },
    { name: "Hessel - Gottlieb", uri: "https://dandre.info" },
    { name: "Barrows - Kuhn", uri: "https://lynn.net" },
    { name: "Kovacek Inc", uri: "http://rozella.biz" },
    { name: "Kub - Walker", uri: "http://christelle.net" },
    { name: "Walter, Schuster and Zemlak", uri: "https://mollie.name" },
    { name: "Huel - Schinner", uri: "http://patricia.net" },
    { name: "Terry Group", uri: "http://terrance.org" },
    { name: "Torp, Cruickshank and Romaguera", uri: "https://edna.info" },
    { name: "Grimes Inc", uri: "https://domenick.biz" },
    { name: "Casper - Runolfsdottir", uri: "http://arvilla.name" },
    { name: "Wolf - Sipes", uri: "http://zackary.biz" },
    { name: "Bauch and Sons", uri: "https://bernard.info" },
    { name: "Mertz - Maggio", uri: "http://leola. biz" },
    { name: "Langosh - Breitenberg", uri: "https://mariela.info" },
    { name: "McCullough and Sons", uri: "https://gabe.org" },
    { name: "Paucek - Rutherford", uri: "http://josianne.org" },
    { name: "Carter, Mohr and Beer", uri: "http://mallie.com" },
    { name: "Davis - Dicki", uri: "http://chadd.com" },
    { name: "Pouros - Murray", uri: "http://karina.biz" },
    { name: "Schumm - Homenick", uri: "https://percival.org" },
    { name: "Reinger - Bins", uri: "http://maia.com" },
    { name: "Jerde - Bradtke", uri: "https://francisca.biz" },
    { name: "MacGyver, Hodkiewicz and Schaden", uri: "http://ambrose.biz" },
    { name: "Hickle Group", uri: "http://merritt.org" },
    { name: "Vandervort, Nicolas and Schultz", uri: "http://margarita.org" },
    { name: "Kreiger LLC", uri: "https://adrien.net" },
    { name: "Wilderman - Hauck", uri: "http://adaline.org" },
    { name: "Lebsack - Schaden", uri: "https://ken.com" },
    { name: "Emmerich Inc", uri: "http://ashlynn.com" },
    { name: "Haley and Sons", uri: "http://ashton.net" },
    { name: "Rogahn, Weber and Howell", uri: "http://joany.info" },
    { name: "Kuphal Inc", uri: "http://adalberto.net" },
    { name: "Wisoky, Rau and Fritsch", uri: "http://sim.name" },
    { name: "Huels, Hoeger and Rutherford", uri: "http://wade.org" },
    { name: "McClure - Fisher", uri: "http://montana.net" },
    { name: "Ruecker - Barton", uri: "https://carmel.org" },
    { name: "Runte - Sanford", uri: "https://foster.net" },
    { name: "Langosh - Zboncak", uri: "https://maude.biz" },
    { name: "Ondricka Group", uri: "https://america.com" },
    { name: "Klocko - Hirthe", uri: "http://barrett.net" },
    { name: "Spinka, Hackett and Ratke", uri: "http://kaden.com" },
    { name: "Emard, Schaden and Koepp", uri: "http://jailyn.net" },
    { name: "Windler, Hodkiewicz and Bosco", uri: "http://aniyah.name" },
    { name: "Fritsch and Sons", uri: "http://harry.name" },
    { name: "Lindgren - Hegmann", uri: "https://asa.name" },
    { name: "Stanton - Kemmer", uri: "http://arlie.name" },
    { name: "Langworth, Davis and Dare", uri: "https://zoe.name" },
    { name: "Hudson, Batz and Hansen", uri: "https://hunter.biz" },
    { name: "Greenfelder Group", uri: "http://camden.info" },
    { name: "Casper LLC", uri: "https://irma.info" },
    { name: "Lind, Streich and Bauch", uri: "http://scot.name" },
    { name: "Koepp, Kunze and Beahan", uri: "http://jovani.biz" },
    { name: "Williamson - Walker", uri: "http://monte.info" },
    { name: "Wiza, West and Cormier", uri: "http://maybell.info" },
    { name: "Lang and Sons", uri: "https://margie.org" },
    { name: "Pagac - Ratke", uri: "http://zachary.org" },
    { name: "Dickinson Group", uri: "http://wilford.biz" },
    { name: "Effertz LLC", uri: "http://yolanda.org" },
    { name: "Dach, Pacocha and Roberts", uri: "https://valentin.name" },
    { name: "Hoppe, Ortiz and Bahringer", uri: "https://thelma.info" },
    { name: "Stracke - Cassin", uri: "https://dayna.info" },
    { name: "Harber and Sons", uri: "https://ericka.com" },
    { name: "Wehner - Dickinson", uri: "https://mariana.net" },
    { name: "Casper, Cremin and Marvin", uri: "https://april.info" },
    { name: "Grady, Beier and Collins", uri: "http://colt.biz" },
    { name: "Hessel and Sons", uri: "http://kali.net" },
    { name: "Ondricka LLC", uri: "http://destiney.com" },
    { name: "Schaden, Runolfsdottir and Bayer", uri: "https://shanon.com" },
    { name: "Torp - Schneider", uri: "http://thad.biz" },
    { name: "Bins - Bins", uri: "https://luisa.org" },
    { name: "Mohr, Sipes and Bergnaum", uri: "http://arnoldo.com" },
    { name: "Shanahan, Dicki and Wuckert", uri: "http://malinda.info" },
    { name: "Breitenberg, Greenholt and Gorczany", uri: "https://johanna.com" },
    { name: "Littel, Borer and Huels", uri: "https://concepcion.org" },
    { name: "Parisian Inc", uri: "http://susie.biz" },
    { name: "Mante Inc", uri: "https://franz.net" },
    { name: "Rogahn - Kris", uri: "https://mariana.net" },
    { name: "Rutherford, Jenkins and O'Conner", uri: "https://alicia.info" },
    { name: "Heaney Inc", uri: "http://lloyd.org" },
    { name: "Kris Group", uri: "https://laverne.net" },
    { name: "Renner and Sons", uri: "https://joesph.info" },
    { name: "Kuhlman, Feil and McCullough", uri: "http://lucile.info" },
    { name: "Dach LLC", uri: "https://melisa.info" },
    { name: "Smith, Rath and Mertz", uri: "http://gustave.biz" },
    { name: "Weber - Greenfelder", uri: "http://barry.info" },
    { name: "Bergnaum, Erdman and Shields", uri: "https://eldred.info" },
    { name: "Hauck, O'Hara and Mante", uri: "https://tatum.biz" },
    { name: "Runolfsdottir LLC", uri: "http://naomi.name" },
    { name: "Lakin, Daugherty and Klocko", uri: "http://susana.net" },
    { name: "Von - Fay", uri: "http://kariane.name" },
    { name: "Bode - Huels", uri: "http://kasey.info" },
    { name: "Connelly - Schmitt", uri: "http://hollis.org" },
    { name: "Glover and Sons", uri: "http://marques.net" },
    { name: "Cole LLC", uri: "https://levi.com" },
    { name: "Ondricka and Sons", uri: "https://lexie.info" },
    { name: "Rutherford, Crooks and Orn", uri: "https://fritz.info" },
    { name: "Kutch Inc", uri: "http://rudy.com" },
    { name: "Pfannerstill, Hahn and Ullrich", uri: "https://della.name" },
    { name: "Thompson, Zulauf and Yost", uri: "http://jeremie.name" },
    { name: "Lynch, Dietrich and Boyle", uri: "http://casandra.biz" },
    { name: "Heaney, Simonis and Witting", uri: "https://kobe.biz" },
    { name: "Emmerich Group", uri: "https://rubie.org" },
    { name: "Wintheiser - Herman", uri: "https://jermaine.net" },
    { name: "Fisher, Bogisich and Dare", uri: "http://shemar.name" },
    { name: "Baumbach - Donnelly", uri: "https://garland.org" },
    { name: "Halvorson - Shanahan", uri: "http://quinten.info" },
    { name: "Hirthe Inc", uri: "https://shane.com" },
    { name: "Zemlak Group", uri: "https://hermann.net" },
    { name: "Durgan, Koepp and Glover", uri: "http://delia.org" },
    { name: "Johnson - O'Kon", uri: "http://celine.com" },
    { name: "Wolff, Lehner and Schamberger", uri: "http://kraig.com" },
    { name: "Streich, Morissette and Sawayn", uri: "http://mohamed.info" },
    { name: "Reichel LLC", uri: "https://derrick.info" },
    { name: "Barton and Sons", uri: "http://irving.org" },
    { name: "Boyle - Connelly", uri: "https://lester.com" },
    { name: "Hodkiewicz Group", uri: "https://annabel.biz" },
    { name: "Reynolds, Larson and O'Reilly", uri: "https://marisol.net" },
    { name: "Bashirian, Simonis and Bode", uri: "http://reta.name" },
    { name: "Dickinson Inc", uri: "https://bette.biz" },
    { name: "Koelpin - Bosco", uri: "http://rashad.biz" },
    { name: "Grant - Pouros", uri: "https://jerrod.info" },
    { name: "Stehr - Kuhic", uri: "http://katheryn.net" },
    { name: "Crooks, Batz and Ritchie", uri: "http://makenzie.name" },
    { name: "Batz - Baumbach", uri: "http://eduardo.biz" },
    { name: "White, Bauch and Stehr", uri: "http://richard.name" },
    { name: "Hane and Sons", uri: "http://eleanora.info" },
    { name: "Klein, Pollich and Koelpin", uri: "https://lucile.net" },
    { name: "Hackett - Stroman", uri: "http://myles.biz" },
    { name: "Marquardt, Pfannerstill and Lehner", uri: "https://dorthy.biz" },
    { name: "Doyle - Lockman", uri: "https://angelita.biz" },
    { name: "Powlowski - Reynolds", uri: "http://genevieve.net" },
    { name: "Auer - Weimann", uri: "http://orin.biz" },
    { name: "O'Connell, Johnston and Weimann", uri: "https://magdalen.biz" },
    { name: "Krajcik - Adams", uri: "http://linnea.info" },
    { name: "Monahan, Kshlerin and Boyer", uri: "https://gino.name" },
    { name: "Schroeder, Lind and Feeney", uri: "https://gerardo.info" },
    { name: "Jacobson, Paucek and Ondricka", uri: "http://werner.info" },
    { name: "Beahan - Mayer", uri: "https://jean.info" },
    { name: "Jast Group", uri: "https://chadd.info" },
    { name: "Hansen Inc", uri: "http://kara.name" },
    { name: "Wilkinson - Carter", uri: "http://johnnie.com" },
    { name: "Shanahan - Reichel", uri: "https://tre.net" },
    { name: "Bashirian LLC", uri: "https://leonora.info" },
    { name: "Kohler, Heller and Smith", uri: "http://federico.net" },
    { name: "Lubowitz - Gutmann", uri: "https://yasmine.com" },
    { name: "Leffler and Sons", uri: "http://selina.net" },
    { name: "Jast, McClure and Runolfsdottir", uri: "http://logan.net" },
    { name: "Dach, McDermott and O'Kon", uri: "http://fannie.info" },
    { name: "Bailey Group", uri: "https://regan.org" },
    { name: "Mayert, Boyer and Mayert", uri: "http://richmond.com" },
    { name: "Prohaska - Gerlach", uri: "https://daphnee.biz" },
    { name: "Batz - Huels", uri: "https://dorthy.biz" },
    { name: "Feeney - Wisoky", uri: "https://haylie.name" },
    { name: "Volkman - Cassin", uri: "http://marcelle.biz" },
    { name: "Hilll and Sons", uri: "http://trycia.name" },
    { name: "Botsford and Sons", uri: "https://abagail.org" },
    { name: "Funk Group", uri: "https://randall.name" },
    { name: "Heathcote - Kuhn", uri: "http://tania.name" },
    { name: "Abshire and Sons", uri: "http://jolie.net" },
    { name: "Larson Group", uri: "https://hanna.net" },
    { name: "Blanda - Cassin", uri: "http://ora.info" },
    { name: "Hintz, Langosh and Waelchi", uri: "http://carolanne.biz" },
    { name: "Schoen - Jerde", uri: "https://lila.info" },
    { name: "Windler - McDermott", uri: "https://gretchen.org" },
    { name: "Bins LLC", uri: "http://greyson.net" },
    { name: "Yundt - Heller", uri: "http://kariane.org" },
    { name: "Reynolds, Senger and Zieme", uri: "http://jacinto.biz" },
    { name: "Reichert, Wyman and Cartwright", uri: "https://torey.info" },
    { name: "Heathcote - Medhurst", uri: "https://kelley.name" },
    { name: "Okuneva - Armstrong", uri: "http://wilhelm.info" },
    { name: "Wilkinson, Cormier and Borer", uri: "https://jammie.info" },
    { name: "DuBuque, Goyette and Smitham", uri: "https://jaleel.net" },
    { name: "Brakus, Paucek and Stokes", uri: "http://efren.name" },
    { name: "Jakubowski - Green", uri: "http://cecilia.net" },
    { name: "Towne, Rempel and Grant", uri: "https://alene.com" },
    { name: "Pfannerstill, Shanahan and Hirthe", uri: "https://eliseo.net" },
    { name: "Fisher Group", uri: "https://roscoe.org" },
    { name: "Runolfsdottir, Champlin and Brekke", uri: "https://rudolph.name" },
    { name: "Jacobs Inc", uri: "http://cruz.net" },
    { name: "Sporer, Kerluke and Becker", uri: "https://haleigh.org" },
    { name: "Yundt and Sons", uri: "http://theron.name" },
    { name: "Metz, Farrell and Kassulke", uri: "https://tomas.com" },
    { name: "Morissette - O'Connell", uri: "https://claudia.biz" },
    { name: "Hyatt Group", uri: "https://alayna.name" },
    { name: "Wiza Group", uri: "https://frankie.name" },
    { name: "Skiles, Crona and Haag", uri: "http://tyrese.org" },
    { name: "Mann and Sons", uri: "https://amparo.  name" },
    { name: "Bednar, Kuhlman and Collier", uri: "https://blanca.net" },
    { name: "Wiegand, Schmitt and Quitzon", uri: "https://bethel.biz" },
    { name: "Crona Group", uri: "http://myrtice.info" },
    { name: "Russel and Sons", uri: "https://adalberto.org" },
    { name: "Jerde, Bailey and Gleichner", uri: "http://rachelle.net" },
    { name: "Tremblay LLC", uri: "https://karlie.info" },
    { name: "Lang, Rau and Lynch", uri: "https://hilton.org" },
    { name: "Spinka and Sons", uri: "https://johanna.com" },
    { name: "Lowe, Lang and Leannon", uri: "http://woodrow.biz" },
    { name: "Lindgren and Sons", uri: "https://damaris.biz" },
    { name: "Konopelski Inc", uri: "http://albin.name" },
    { name: "Jacobson and Sons", uri: "https://gonzalo.net" },
    { name: "Konopelski - Harris", uri: "https://leland.org" },
    { name: "Cremin and Sons", uri: "https://imani.info" },
    { name: "Bayer, Zieme and Ferry", uri: "http://arianna.name" },
    { name: "Schultz - Kuhlman", uri: "https://amber.info" },
    { name: "Paucek - Wyman", uri: "http://daniela.info" },
    { name: "Kerluke - Mohr", uri: "http://chris.info" },
    { name: "Dach, Hettinger and Trantow", uri: "http://zoie.org" },
    { name: "Raynor, Douglas and Dach", uri: "http://david.info" },
    { name: "Weissnat Group", uri: "http://elroy.info" },
    { name: "Gibson, Hudson and Barton", uri: "https://kacey.org" },
    { name: "Konopelski, Mitchell and Block", uri: "http://deangelo.name" },
    { name: "Roob, Kiehn and Kertzmann", uri: "http://bryon.info" },
    { name: "Schulist Inc", uri: "http://shawn.info" },
    { name: "Willms - Bogan", uri: "https://lorena.name" },
    { name: "Raynor - Shields", uri: "https://kolby.com" },
    { name: "Borer Group", uri: "https://eldred.org" },
    { name: "King LLC", uri: "https://adelbert.org" },
    { name: "Rosenbaum Group", uri: "http://marlen.org" },
    { name: "Tromp - Kris", uri: "http://rachelle.org" },
    { name: "Reichel, Prosacco and Nolan", uri: "https://janice.info" },
    { name: "McClure Inc", uri: "https://dahlia.biz" },
    { name: "Johnson - Kunde", uri: "http://maximilian.org" },
    { name: "Ernser LLC", uri: "http://braden.biz" },
    { name: "McClure, Langosh and Reichert", uri: "https://trent.net" },
    { name: "Howe - Quitzon", uri: "http://queenie.biz" },
    { name: "Roberts Group", uri: "http://max.com" },
    { name: "Kautzer LLC", uri: "http://maci.com" },
    { name: "Crooks - Jast", uri: "https://haylee.biz" },
    { name: "Stokes Inc", uri: "http://kenya.com" },
    { name: "Trantow Inc", uri: "https://antonetta.com" },
    { name: "Daniel, Schimmel and Feest", uri: "http://krista.biz" },
    { name: "Haag - Heaney", uri: "https://noel.com" },
    { name: "Weber - Lindgren", uri: "http://dedric.info" },
    { name: "Lynch, Ullrich and McGlynn", uri: "https://shanna.net" },
    { name: "Jaskolski and Sons", uri: "http://effie.org" },
    { name: "Thompson Inc", uri: "http://armani.info" },
    { name: "Orn, Okuneva and Klocko", uri: "http://constance.com" },
    { name: "Reilly - Abernathy", uri: "https://israel.org" },
    { name: "Hahn Inc", uri: "https://brad.org" },
    { name: "Moore, Littel and Murray", uri: "http://mozell.org" },
    { name: "Quigley, Schmidt and Mills", uri: "https://anjali.net" },
    { name: "Waelchi Inc", uri: "https://gussie.name" },
    { name: "King - Doyle", uri: "https://mariano.org" },
    { name: "Franecki, Stehr and Wiza", uri: "http://john.org" },
    { name: "O'Conner and Sons", uri: "https://winfield.net" },
    { name: "Herzog, Leuschke and Boyle", uri: "https://kenyon.org" },
    { name: "Cremin Inc", uri: "https://hillard.net" },
    { name: "Moore - Cruickshank", uri: "https://aleen.net" },
    { name: "Pfannerstill Inc", uri: "https://chasity.info" },
    { name: "Kub - Klocko", uri: "http://lydia.org" },
    { name: "Quigley and Sons", uri: "https://delta.net" },
    { name: "Wyman - Heller", uri: "http://allen.info" },
    { name: "Jacobi - Kshlerin", uri: "http://randy.net" },
    { name: "Grant, Rodriguez and Lueilwitz", uri: "http://brenna.name" },
    { name: "Gorczany, Hagenes and Effertz", uri: "https://edythe.org" },
    { name: "Goldner, Buckridge and Rau", uri: "http://coy.name" },
    { name: "Kovacek Inc", uri: "http://wilhelm.net" },
    { name: "Herzog, Wintheiser and Stark", uri: "http://juanita.org" },
    { name: "Bayer - Fisher", uri: "https://triston.info" },
    { name: "Jenkins, Maggio and Steuber", uri: "http://lorna.net" },
    { name: "Steuber, Goldner and Kiehn", uri: "https://kiley.name" },
    { name: "Barrows - Kertzmann", uri: "http://raphael.com" }
  ]
}
