module.exports.OBJECT_LIKE = 'map|weakmap'
module.exports.PRIMITIVES = 'boolean|string|number|symbol'
module.exports.ERRORS = 'error|evalerror|internalerror|rangeerror|referenceerror|syntaxerror|typeerror|urierror'
module.exports.OTHER_TYPES = 'date|regexp|function'
module.exports.ARRAY_LIKE = 'array|int8array|uint8array|uint8clampedarray|int16array|uint16array|int32array|float32array|float64array|set|weakset'
